---
title: "Visit Scotland Notebook"
output: html_notebook
---

## Load Libraries

```{r}
library(tidyverse)
library(here)
library(sf)
library(infer)
```

## Run Cleaning Script

```{r}
source(here("scripts/cleaning_script.R"))
```

## Read In Clean Data

```{r}

regional_domestic_tourism_all <- read_csv(here("data/clean_data/regional_domestic_tourism_all_clean.csv"))
regional_domestic_tourism_individual <- read_csv(here("data/clean_data/regional_domestic_tourism_individual_clean.csv"))
local_authority_geo <- st_read(dsn = "data/geo_data/", layer = "pub_las")

```

## Trends Over Time

### Domestic Tourism / Visits

```{r}

regional_domestic_tourism_all %>%
  ggplot(aes(x = date_code, y = visits)) +
  geom_line(group = 1) +
  geom_point(aes(colour = visits_change_label), 
             show.legend = FALSE,
             size = 4) +
  labs(x = "\n Year Range",
       y = "Visitors (Thousands) \n",
       title = "Average Annual Number of Domestic Vistors",
       subtitle = "3 Year Average")

```

### Domestic Tourism / Expenditure

```{r}

regional_domestic_tourism_all %>%
  ggplot(aes(x = date_code, y = expenditure)) +
  geom_line(group = 1) +
  geom_point(aes(colour = exp_change_label), 
             show.legend = FALSE,
             size = 4) +
  labs(x = "\n Year Range",
       y = "Expenditure (Million GBP) \n",
       title = "Average Annual Expenditure of Domestic Vistors",
       subtitle = "3 Year Average")

```
### Domestic Tourism / Nights Stayed

```{r}

regional_domestic_tourism_all %>%
  ggplot(aes(x = date_code, y = nights)) +
  geom_line(group = 1) +
  geom_point(aes(colour = nights_change_label), 
             show.legend = FALSE,
             size = 4) +
  labs(x = "\n Year Range",
       y = "Nights (Thousands) \n",
       title = "Average Annual Nights Stayed by Domestic Vistors",
       subtitle = "3 Year Average")

```

### Domestic Tourism / Expenditure per Visit

```{r}
regional_domestic_tourism_all %>%
  ggplot(aes(x = date_code, y = exp_per_visit)) +
  geom_line(group = 1) +
  geom_point(aes(colour = exp_per_visit_label), 
             show.legend = FALSE,
             size = 4) +
  labs(x = "\n Year Range",
       y = "3x Year Average Expenditure per Visit (Thousands) \n",
       title = "Average Expenditure Per Visit Domestic Vistors",
       subtitle = "3 Year Average")
```

### Which Regions Are Domestic Tourists Visiting

#### Average Visits By Region

##### Stats

```{r}

regional_domestic_tourism_all %>% 
  summarise(mean_annual_visits = mean(visits))

# Mean Annual Visits: ~12,337,000

regional_domestic_tourism_all %>%
  rep_sample_n(size = 12, replace = TRUE, reps = 5000) %>%
  summarise(mean_visits = mean(visits)) %>% 
  get_confidence_interval(level = 0.95, type = "percentile")

# 95% CI: 12,175,250 - 12,507,590
```

##### Map

```{r}

regional_data_joined %>% 
  group_by(year, code) %>% 
  summarise(mean_visits = mean(visits)) %>% 
  ggplot(aes(fill = mean_visits)) + 
  geom_sf() +
  labs(
    x = "Longitude",
    y = "Latitude",
    title = "Average Annual Number of Domestic Vistors",
    subtitle = "By Region",
    fill = "Visits (Thousands)"
  ) +
  theme(panel.background = element_rect(fill = "white"))

```


#### Expenditure by Region

##### Stats

```{r}
regional_domestic_tourism_all %>% 
  summarise(mean_annual_exp = mean(expenditure))

# Mean Annual Expenditure: 

regional_domestic_tourism_all %>%
  rep_sample_n(size = 12, replace = TRUE, reps = 5000) %>%
  summarise(mean_annual_exp = mean(expenditure)) %>% 
  get_confidence_interval(level = 0.95, type = "percentile")

# 95% CI: 1
```

##### Map

```{r}
regional_data_joined %>% 
  group_by(year, code) %>% 
  summarise(mean_exp = mean(expenditure)) %>% 
  ggplot(aes(fill = mean_exp)) + 
  geom_sf() +
  labs(
    x = "Longitude",
    y = "Latitude",
    title = "Average Annual Expenditure of Domestic Vistors",
    subtitle = "By Region",
    fill = "Expenditure (Million GBP)"
  ) +
  theme(panel.background = element_rect(fill = "white"))
```





### Line Plot Over Time











